spring:
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/messagesdb
    username: postgres
    password: postgrespw
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: messages-group
kafka:
  topicName: messages