spring:
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:32769/postgres
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: create-drop